# Generated by Django 6.0.1 on 2026-01-26 11:51

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Page Agenda",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticleIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Index des Articles",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BidulIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Index des Biduls",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="FlexiblePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "contenu",
                    wagtail.fields.StreamField(
                        [
                            ("texte", 0),
                            ("image", 1),
                            ("galerie", 3),
                            ("citation", 4),
                            ("embed", 5),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ul",
                                        "ol",
                                        "blockquote",
                                    ],
                                    "label": "Texte riche",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.ListBlock",
                                (2,),
                                {"label": "Galerie d'images"},
                            ),
                            4: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"label": "Citation"},
                            ),
                            5: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "YouTube, Vimeo, SoundCloud, etc.",
                                    "label": "Média embarqué",
                                },
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Page flexible",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LieuxIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Index des Lieux",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date_publication", models.DateField()),
                (
                    "introduction",
                    models.TextField(blank=True, help_text="Chapô affiché en liste"),
                ),
                (
                    "contenu",
                    wagtail.fields.StreamField(
                        [
                            ("texte", 0),
                            ("image", 1),
                            ("galerie", 3),
                            ("citation", 4),
                            ("embed", 5),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ul",
                                        "ol",
                                        "blockquote",
                                    ],
                                    "label": "Texte riche",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.ListBlock",
                                (2,),
                                {"label": "Galerie d'images"},
                            ),
                            4: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"label": "Citation"},
                            ),
                            5: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "YouTube, Vimeo, SoundCloud, etc.",
                                    "label": "Média embarqué",
                                },
                            ),
                        },
                    ),
                ),
                (
                    "mise_en_avant",
                    models.BooleanField(default=False, help_text="Afficher en une"),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="agenda.auteur",
                    ),
                ),
                (
                    "categories",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, related_name="articles", to="agenda.categorie"
                    ),
                ),
                (
                    "image_principale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "ordering": ["-date_publication"],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="content.articlepage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="articlepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="content.ArticleTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="BidulPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "editorial",
                    models.TextField(
                        blank=True, help_text="Texte d'introduction / édito"
                    ),
                ),
                (
                    "contenu",
                    wagtail.fields.StreamField(
                        [
                            ("texte", 0),
                            ("image", 1),
                            ("galerie", 3),
                            ("citation", 4),
                            ("embed", 5),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ul",
                                        "ol",
                                        "blockquote",
                                    ],
                                    "label": "Texte riche",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.ListBlock",
                                (2,),
                                {"label": "Galerie d'images"},
                            ),
                            4: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"label": "Citation"},
                            ),
                            5: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "YouTube, Vimeo, SoundCloud, etc.",
                                    "label": "Média embarqué",
                                },
                            ),
                        },
                    ),
                ),
                (
                    "bidul",
                    models.OneToOneField(
                        help_text="Sélectionner le numéro du Bidul",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="page",
                        to="agenda.bidul",
                    ),
                ),
                (
                    "couverture",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image de couverture",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        blank=True,
                        help_text="PDF téléchargeable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Bidul",
                "verbose_name_plural": "Pages Bidul",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page d'accueil",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="LieuPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "contenu",
                    wagtail.fields.StreamField(
                        [
                            ("texte", 0),
                            ("image", 1),
                            ("galerie", 3),
                            ("citation", 4),
                            ("embed", 5),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ul",
                                        "ol",
                                        "blockquote",
                                    ],
                                    "label": "Texte riche",
                                },
                            ),
                            1: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.ListBlock",
                                (2,),
                                {"label": "Galerie d'images"},
                            ),
                            4: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"label": "Citation"},
                            ),
                            5: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "YouTube, Vimeo, SoundCloud, etc.",
                                    "label": "Média embarqué",
                                },
                            ),
                        },
                    ),
                ),
                (
                    "lieu",
                    models.OneToOneField(
                        help_text="Sélectionner le lieu",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="page",
                        to="agenda.lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Lieu",
                "verbose_name_plural": "Pages Lieux",
            },
            bases=("wagtailcore.page",),
        ),
    ]
