# Generated by Django 6.0.1 on 2026-02-17 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='fichier_pdf',
            field=models.ForeignKey(blank=True, help_text='PDF téléchargeable lié à cet article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Fichier PDF'),
        ),
    ]
