# Generated by Django 6.0.1 on 2026-01-29 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur_primaire', models.CharField(default='#E63946', help_text='Couleur principale', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#1D3557', help_text='Couleur secondaire', max_length=7)),
                ('couleur_accent', models.CharField(default='#F4A261', help_text="Couleur d'accent", max_length=7)),
                ('couleur_fond', models.CharField(default='#F1FAEE', help_text='Couleur de fond', max_length=7)),
                ('couleur_texte', models.CharField(default='#1D3557', help_text='Couleur du texte', max_length=7)),
                ('police_titres', models.CharField(default='Montserrat', help_text='Police Google Fonts pour les titres', max_length=100)),
                ('police_corps', models.CharField(default='Open Sans', help_text='Police Google Fonts pour le corps de texte', max_length=100)),
                ('css_custom', models.TextField(blank=True, help_text='CSS additionnel (avancé)')),
                ('favicon', models.ForeignKey(blank=True, help_text='Favicon 32x32', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, help_text='Logo header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo_footer', models.ForeignKey(blank=True, help_text='Logo footer (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Paramètres du thème',
            },
        ),
    ]
