# Generated by Django 6.0.1 on 2026-01-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bidul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Numéro unique du Bidul", unique=True
                    ),
                ),
                (
                    "mois",
                    models.CharField(
                        help_text="Nom du mois (ex: décembre)", max_length=20
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                ("date_publication", models.DateField()),
                (
                    "nb_evenements",
                    models.PositiveIntegerField(
                        default=0, help_text="Nombre d'événements extraits"
                    ),
                ),
                (
                    "data_indexer",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données brutes de l'extraction (métadonnées, stats)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bidul",
                "verbose_name_plural": "Biduls",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "couleur",
                    models.CharField(
                        default="#E63946",
                        help_text="Code couleur hex (ex: #E63946)",
                        max_length=7,
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nom icône Lucide (ex: music, theater, film)",
                        max_length=50,
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("site_web", models.URLField(blank=True)),
                ("twitter", models.CharField(blank=True, max_length=100)),
                ("instagram", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auteur",
                "verbose_name_plural": "Auteurs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Lieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("code_postal", models.CharField(blank=True, max_length=10)),
                ("ville", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude (ex: 47.9960)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude (ex: 0.1926)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("site_web", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "actif",
                    models.BooleanField(
                        default=True, help_text="Décocher pour masquer ce lieu"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieu",
                "verbose_name_plural": "Lieux",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("date_debut", models.DateField(db_index=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("heure_debut", models.TimeField(blank=True, null=True)),
                ("heure_fin", models.TimeField(blank=True, null=True)),
                (
                    "prix",
                    models.CharField(
                        blank=True, help_text="Ex: Gratuit, 5€, 10-15€", max_length=100
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, help_text="Lien vers plus d'infos"),
                ),
                (
                    "data_source",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données brutes de l'import (Bidul Indexer)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("annule", "Annulé"),
                        ],
                        db_index=True,
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements",
                        to="agenda.categorie",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "source_bidul",
                    models.ForeignKey(
                        blank=True,
                        help_text="Numéro du Bidul d'où provient cet événement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_source",
                        to="agenda.bidul",
                    ),
                ),
                (
                    "lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="agenda.lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["date_debut", "heure_debut"],
            },
        ),
        migrations.AddIndex(
            model_name="lieu",
            index=models.Index(fields=["ville"], name="agenda_lieu_ville_5e53f4_idx"),
        ),
        migrations.AddIndex(
            model_name="lieu",
            index=models.Index(
                fields=["actif", "ville"], name="agenda_lieu_actif_61e206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evenement",
            index=models.Index(
                fields=["date_debut"], name="agenda_even_date_de_c4283a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evenement",
            index=models.Index(
                fields=["statut", "date_debut"], name="agenda_even_statut_0e1b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evenement",
            index=models.Index(
                fields=["lieu", "date_debut"], name="agenda_even_lieu_id_e0bba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evenement",
            index=models.Index(
                fields=["source_bidul"], name="agenda_even_source__69e294_idx"
            ),
        ),
    ]
