# Generated by Django 6.0.1 on 2026-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidul",
            name="mois",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "janvier"),
                    (2, "février"),
                    (3, "mars"),
                    (4, "avril"),
                    (5, "mai"),
                    (6, "juin"),
                    (7, "juillet"),
                    (8, "août"),
                    (9, "septembre"),
                    (10, "octobre"),
                    (11, "novembre"),
                    (12, "décembre"),
                ],
                help_text="Mois de parution (1-12)",
            ),
        ),
        migrations.AddIndex(
            model_name="lieu",
            index=models.Index(
                fields=["latitude", "longitude"], name="agenda_lieu_latitud_6bb036_idx"
            ),
        ),
    ]
